"""Pre-built glossary data for common academic domains (HK academic context)."""

from __future__ import annotations

BUILTIN_GLOSSARIES: dict[str, list[dict]] = {
    "stem": [
        {"term_en": "algorithm", "term_tc": "演算法", "term_sc": "算法"},
        {"term_en": "artificial intelligence", "term_tc": "人工智能", "term_sc": "人工智能"},
        {"term_en": "machine learning", "term_tc": "機器學習", "term_sc": "机器学习"},
        {"term_en": "deep learning", "term_tc": "深度學習", "term_sc": "深度学习"},
        {"term_en": "neural network", "term_tc": "神經網絡", "term_sc": "神经网络"},
        {"term_en": "information technology", "term_tc": "資訊科技", "term_sc": "信息技术"},
        {"term_en": "software", "term_tc": "軟件", "term_sc": "软件"},
        {"term_en": "hardware", "term_tc": "硬件", "term_sc": "硬件"},
        {"term_en": "database", "term_tc": "數據庫", "term_sc": "数据库"},
        {"term_en": "bandwidth", "term_tc": "頻寬", "term_sc": "带宽"},
        {"term_en": "semiconductor", "term_tc": "半導體", "term_sc": "半导体"},
        {"term_en": "quantum computing", "term_tc": "量子計算", "term_sc": "量子计算"},
        {"term_en": "cybersecurity", "term_tc": "網絡安全", "term_sc": "网络安全"},
        {"term_en": "nanotechnology", "term_tc": "納米技術", "term_sc": "纳米技术"},
        {"term_en": "regression analysis", "term_tc": "回歸分析", "term_sc": "回归分析"},
        {"term_en": "standard deviation", "term_tc": "標準差", "term_sc": "标准差"},
        {"term_en": "hypothesis testing", "term_tc": "假設檢定", "term_sc": "假设检验"},
        {"term_en": "variable", "term_tc": "變量", "term_sc": "变量"},
        {"term_en": "simulation", "term_tc": "模擬", "term_sc": "模拟"},
        {"term_en": "parameter", "term_tc": "參數", "term_sc": "参数"},
    ],
    "medicine": [
        {"term_en": "diabetes mellitus", "term_tc": "糖尿病", "term_sc": "糖尿病"},
        {"term_en": "hypertension", "term_tc": "高血壓", "term_sc": "高血压"},
        {"term_en": "cardiovascular disease", "term_tc": "心血管疾病", "term_sc": "心血管疾病"},
        {"term_en": "randomised controlled trial", "term_tc": "隨機對照試驗", "term_sc": "随机对照试验"},
        {"term_en": "meta-analysis", "term_tc": "薈萃分析", "term_sc": "荟萃分析"},
        {"term_en": "cohort study", "term_tc": "隊列研究", "term_sc": "队列研究"},
        {"term_en": "prevalence", "term_tc": "患病率", "term_sc": "患病率"},
        {"term_en": "incidence", "term_tc": "發病率", "term_sc": "发病率"},
        {"term_en": "prognosis", "term_tc": "預後", "term_sc": "预后"},
        {"term_en": "pathology", "term_tc": "病理學", "term_sc": "病理学"},
        {"term_en": "pharmacology", "term_tc": "藥理學", "term_sc": "药理学"},
        {"term_en": "immunology", "term_tc": "免疫學", "term_sc": "免疫学"},
        {"term_en": "oncology", "term_tc": "腫瘤學", "term_sc": "肿瘤学"},
        {"term_en": "clinical trial", "term_tc": "臨床試驗", "term_sc": "临床试验"},
        {"term_en": "adverse effect", "term_tc": "不良反應", "term_sc": "不良反应"},
        {"term_en": "informed consent", "term_tc": "知情同意", "term_sc": "知情同意"},
        {"term_en": "placebo", "term_tc": "安慰劑", "term_sc": "安慰剂"},
        {"term_en": "epidemiology", "term_tc": "流行病學", "term_sc": "流行病学"},
        {"term_en": "aetiology", "term_tc": "病因學", "term_sc": "病因学"},
        {"term_en": "diagnosis", "term_tc": "診斷", "term_sc": "诊断"},
    ],
    "law": [
        {"term_en": "ordinance", "term_tc": "條例", "term_sc": "条例"},
        {"term_en": "contract", "term_tc": "合約", "term_sc": "合同"},
        {"term_en": "tort", "term_tc": "侵權法", "term_sc": "侵权法"},
        {"term_en": "jurisdiction", "term_tc": "司法管轄權", "term_sc": "司法管辖权"},
        {"term_en": "plaintiff", "term_tc": "原告", "term_sc": "原告"},
        {"term_en": "defendant", "term_tc": "被告", "term_sc": "被告"},
        {"term_en": "judicial review", "term_tc": "司法覆核", "term_sc": "司法审查"},
        {"term_en": "common law", "term_tc": "普通法", "term_sc": "普通法"},
        {"term_en": "statute", "term_tc": "成文法", "term_sc": "成文法"},
        {"term_en": "precedent", "term_tc": "判例", "term_sc": "判例"},
        {"term_en": "arbitration", "term_tc": "仲裁", "term_sc": "仲裁"},
        {"term_en": "intellectual property", "term_tc": "知識產權", "term_sc": "知识产权"},
        {"term_en": "negligence", "term_tc": "疏忽", "term_sc": "过失"},
        {"term_en": "liability", "term_tc": "法律責任", "term_sc": "法律责任"},
        {"term_en": "injunction", "term_tc": "禁制令", "term_sc": "禁令"},
        {"term_en": "litigation", "term_tc": "訴訟", "term_sc": "诉讼"},
        {"term_en": "due diligence", "term_tc": "盡職審查", "term_sc": "尽职调查"},
        {"term_en": "fiduciary duty", "term_tc": "受信責任", "term_sc": "信义义务"},
        {"term_en": "memorandum of understanding", "term_tc": "諒解備忘錄", "term_sc": "谅解备忘录"},
        {"term_en": "court of appeal", "term_tc": "上訴法庭", "term_sc": "上诉法院"},
    ],
    "business": [
        {"term_en": "return on investment", "term_tc": "投資回報率", "term_sc": "投资回报率"},
        {"term_en": "shareholder", "term_tc": "股東", "term_sc": "股东"},
        {"term_en": "turnover", "term_tc": "營業額", "term_sc": "营业额"},
        {"term_en": "market capitalisation", "term_tc": "市值", "term_sc": "市值"},
        {"term_en": "corporate governance", "term_tc": "企業管治", "term_sc": "公司治理"},
        {"term_en": "initial public offering", "term_tc": "首次公開招股", "term_sc": "首次公开发行"},
        {"term_en": "supply chain management", "term_tc": "供應鏈管理", "term_sc": "供应链管理"},
        {"term_en": "stakeholder", "term_tc": "持份者", "term_sc": "利益相关者"},
        {"term_en": "mergers and acquisitions", "term_tc": "併購", "term_sc": "并购"},
        {"term_en": "venture capital", "term_tc": "創業投資", "term_sc": "风险投资"},
        {"term_en": "gross domestic product", "term_tc": "本地生產總值", "term_sc": "国内生产总值"},
        {"term_en": "balance sheet", "term_tc": "資產負債表", "term_sc": "资产负债表"},
        {"term_en": "cash flow", "term_tc": "現金流", "term_sc": "现金流"},
        {"term_en": "depreciation", "term_tc": "折舊", "term_sc": "折旧"},
        {"term_en": "equity", "term_tc": "股本", "term_sc": "股本"},
        {"term_en": "dividend", "term_tc": "股息", "term_sc": "股息"},
        {"term_en": "fiscal policy", "term_tc": "財政政策", "term_sc": "财政政策"},
        {"term_en": "monetary policy", "term_tc": "貨幣政策", "term_sc": "货币政策"},
        {"term_en": "inflation", "term_tc": "通脹", "term_sc": "通胀"},
        {"term_en": "competitive advantage", "term_tc": "競爭優勢", "term_sc": "竞争优势"},
    ],
    "social_science": [
        {"term_en": "qualitative research", "term_tc": "質性研究", "term_sc": "定性研究"},
        {"term_en": "quantitative research", "term_tc": "量化研究", "term_sc": "定量研究"},
        {"term_en": "ethnography", "term_tc": "民族誌", "term_sc": "民族志"},
        {"term_en": "social capital", "term_tc": "社會資本", "term_sc": "社会资本"},
        {"term_en": "self-efficacy", "term_tc": "自我效能感", "term_sc": "自我效能感"},
        {"term_en": "cognitive development", "term_tc": "認知發展", "term_sc": "认知发展"},
        {"term_en": "socioeconomic status", "term_tc": "社會經濟地位", "term_sc": "社会经济地位"},
        {"term_en": "sampling", "term_tc": "抽樣", "term_sc": "抽样"},
        {"term_en": "statistical significance", "term_tc": "統計顯著性", "term_sc": "统计显著性"},
        {"term_en": "validity", "term_tc": "效度", "term_sc": "效度"},
        {"term_en": "reliability", "term_tc": "信度", "term_sc": "信度"},
        {"term_en": "informed consent", "term_tc": "知情同意", "term_sc": "知情同意"},
        {"term_en": "triangulation", "term_tc": "三角驗證", "term_sc": "三角验证"},
        {"term_en": "phenomenology", "term_tc": "現象學", "term_sc": "现象学"},
        {"term_en": "grounded theory", "term_tc": "扎根理論", "term_sc": "扎根理论"},
        {"term_en": "discourse analysis", "term_tc": "話語分析", "term_sc": "话语分析"},
        {"term_en": "longitudinal study", "term_tc": "縱向研究", "term_sc": "纵向研究"},
        {"term_en": "cross-sectional study", "term_tc": "橫斷面研究", "term_sc": "横断面研究"},
        {"term_en": "institutional review board", "term_tc": "倫理審查委員會", "term_sc": "伦理审查委员会"},
        {"term_en": "structural equation modelling", "term_tc": "結構方程模型", "term_sc": "结构方程模型"},
    ],
}


def load_builtin_glossary(domain: str) -> list[dict]:
    """Return the built-in glossary for a domain.

    Args:
        domain: One of stem, medicine, law, business, social_science.

    Returns:
        List of term dicts with keys term_en, term_tc, term_sc.
        Returns an empty list for unknown domains.
    """
    return [dict(t) for t in BUILTIN_GLOSSARIES.get(domain, [])]
