"""Jinja2-based project scaffolding for HK-specific integrations."""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

from jinja2 import Environment, BaseLoader

from vibe_coder.hk_dev_kit.generator.config_builder import ConfigBuilder

_README_TEMPLATE = textwrap.dedent("""\
    # {{ project_name }}

    > Auto-generated by HKDevKit scaffolder

    ## Integrations

    {% for integration in integrations -%}
    - {{ integration }}
    {% endfor %}

    ## Quick Start

    ```bash
    python -m venv .venv && source .venv/bin/activate
    pip install -r requirements.txt
    cp .env.example .env   # then fill in your keys
    {% if framework == "fastapi" -%}
    uvicorn app:app --reload
    {% elif framework == "flask" -%}
    flask run --reload
    {% else -%}
    python main.py
    {% endif -%}
    ```

    ## Environment Variables

    See `.env.example` for all required configuration.
""")

_ENV_TEMPLATE = textwrap.dedent("""\
    # {{ project_name }} — environment variables
    # Copy to .env and fill in real values

    {% for key, desc in env_vars.items() -%}
    # {{ desc }}
    {{ key }}=
    {% endfor %}
""")

_REQUIREMENTS_TEMPLATE = textwrap.dedent("""\
    # {{ project_name }} dependencies
    {% for pkg in packages -%}
    {{ pkg }}
    {% endfor %}
""")

_FASTAPI_APP_TEMPLATE = textwrap.dedent("""\
    \"\"\"{{ project_name }} — FastAPI application.\"\"\"

    from __future__ import annotations

    import os

    from dotenv import load_dotenv
    from fastapi import FastAPI

    load_dotenv()

    app = FastAPI(title="{{ project_name }}")


    @app.get("/health")
    async def health():
        return {"status": "ok"}

    {% if "fps" in integrations %}
    # -- FPS Payment Integration -----------------------------------------------
    from pydantic import BaseModel

    class FPSPayRequest(BaseModel):
        proxy_id: str
        amount: float
        currency: str = "HKD"

    @app.post("/api/fps/pay")
    async def fps_pay(body: FPSPayRequest):
        return {"status": "pending", "proxy_id": body.proxy_id, "amount": body.amount}
    {% endif %}

    {% if "octopus" in integrations %}
    # -- Octopus Payment Integration -------------------------------------------
    @app.post("/api/octopus/pay")
    async def octopus_pay():
        return {"status": "pending"}
    {% endif %}

    {% if "govhk_weather" in integrations %}
    # -- GovHK Weather ---------------------------------------------------------
    import httpx

    @app.get("/api/weather")
    async def weather():
        async with httpx.AsyncClient() as client:
            resp = await client.get(
                "https://data.weather.gov.hk/weatherAPI/opendata/weather.php",
                params={"dataType": "rhrread", "lang": "en"},
            )
            return resp.json()
    {% endif %}
""")

_FLASK_APP_TEMPLATE = textwrap.dedent("""\
    \"\"\"{{ project_name }} — Flask application.\"\"\"

    from __future__ import annotations

    import os

    from dotenv import load_dotenv
    from flask import Flask, jsonify

    load_dotenv()

    app = Flask(__name__)


    @app.route("/health")
    def health():
        return jsonify(status="ok")
""")

_PLAIN_MAIN_TEMPLATE = textwrap.dedent("""\
    \"\"\"{{ project_name }} — main entry point.\"\"\"

    from __future__ import annotations

    import os

    from dotenv import load_dotenv

    load_dotenv()


    def main():
        print("{{ project_name }} is running")


    if __name__ == "__main__":
        main()
""")

_FRAMEWORK_PACKAGES: dict[str, list[str]] = {
    "fastapi": ["fastapi>=0.115", "uvicorn[standard]>=0.32", "python-dotenv>=1.0"],
    "flask": ["flask>=3.0", "python-dotenv>=1.0"],
    "plain": ["python-dotenv>=1.0"],
}

_INTEGRATION_PACKAGES: dict[str, list[str]] = {
    "fps": ["qrcode[pil]>=7.4", "Pillow>=10.0"],
    "octopus": ["httpx>=0.27"],
    "govhk_weather": ["httpx>=0.27"],
    "govhk_transport": ["httpx>=0.27"],
    "govhk_geodata": ["httpx>=0.27"],
}


class ProjectScaffolder:
    """Generate a complete boilerplate project with HK integrations."""

    def __init__(self) -> None:
        self._env = Environment(loader=BaseLoader(), keep_trailing_newline=True)
        self._config_builder = ConfigBuilder()

    def generate(
        self,
        project_name: str,
        framework: str = "fastapi",
        integrations: list[str] | None = None,
        output_dir: str | Path = ".",
    ) -> Path:
        """Scaffold a project directory and return its path."""
        integrations = integrations or []
        root = Path(output_dir) / project_name
        root.mkdir(parents=True, exist_ok=True)

        context: dict[str, Any] = {
            "project_name": project_name,
            "framework": framework,
            "integrations": integrations,
        }

        packages = list(_FRAMEWORK_PACKAGES.get(framework, _FRAMEWORK_PACKAGES["plain"]))
        seen: set[str] = set(packages)
        for intg in integrations:
            for pkg in _INTEGRATION_PACKAGES.get(intg, []):
                if pkg not in seen:
                    packages.append(pkg)
                    seen.add(pkg)
        context["packages"] = packages

        config = self._config_builder.build(integrations)
        context["env_vars"] = config.get("env_vars", {})

        self._write(root / "requirements.txt", _REQUIREMENTS_TEMPLATE, context)
        self._write(root / ".env.example", _ENV_TEMPLATE, context)
        self._write(root / "README.md", _README_TEMPLATE, context)

        if framework == "fastapi":
            self._write(root / "app.py", _FASTAPI_APP_TEMPLATE, context)
        elif framework == "flask":
            self._write(root / "app.py", _FLASK_APP_TEMPLATE, context)
        else:
            self._write(root / "main.py", _PLAIN_MAIN_TEMPLATE, context)

        (root / ".gitignore").write_text(
            ".env\n__pycache__/\n*.pyc\n.venv/\n*.egg-info/\ndist/\n",
            encoding="utf-8",
        )

        return root

    def _write(self, path: Path, template_str: str, context: dict[str, Any]) -> None:
        rendered = self._env.from_string(template_str).render(**context)
        path.write_text(rendered, encoding="utf-8")
